"""
test_skill_quality.py — Validate deeper skill quality beyond frontmatter.

Checks:
- Body has meaningful content (> 200 chars)
- At least one H2 section (## )
- No untracked TODO/FIXME markers
- Skill names referenced in body exist on disk
"""

from __future__ import annotations

import re
from pathlib import Path

import pytest

from conftest import SKILLS_DIR, SKILL_CONTAINER_DIRS, parse_frontmatter


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _all_skill_dirs() -> list[Path]:
    """Collect all skill directories (expanding refs/)."""
    dirs: list[Path] = []
    for d in sorted(SKILLS_DIR.iterdir()):
        if not d.is_dir():
            continue
        if d.name in SKILL_CONTAINER_DIRS:
            for sub in sorted(d.iterdir()):
                if sub.is_dir():
                    dirs.append(sub)
        else:
            dirs.append(d)
    return dirs


def _all_skill_names() -> set[str]:
    """All skill names on disk."""
    return {d.name for d in _all_skill_dirs()}


def _get_body(path: Path) -> str:
    """Extract body content (after frontmatter)."""
    text = path.read_text(encoding="utf-8")
    if text.startswith("---"):
        end = text.find("\n---", 3)
        if end != -1:
            return text[end + 4:].strip()
    return text.strip()


_SKILL_DIRS = _all_skill_dirs()
_SKILL_IDS = [d.name for d in _SKILL_DIRS]

# Skills that are intentionally minimal (reference/wrapper skills)
_MINIMAL_BODY_ALLOWLIST = {"atlas-assist"}  # Generated by build.sh


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@pytest.mark.parametrize("skill_dir", _SKILL_DIRS, ids=_SKILL_IDS)
@pytest.mark.strict
class TestSkillQuality:

    def test_body_has_meaningful_content(self, skill_dir: Path) -> None:
        """Skill body should have > 200 chars of actual content."""
        md = skill_dir / "SKILL.md"
        if not md.exists():
            pytest.skip(f"No SKILL.md in {skill_dir.name}")
        if skill_dir.name in _MINIMAL_BODY_ALLOWLIST:
            pytest.skip(f"{skill_dir.name} is in minimal body allowlist")

        body = _get_body(md)
        assert len(body) > 200, (
            f"Skill '{skill_dir.name}' body is too short ({len(body)} chars). "
            f"Expected > 200 chars of meaningful content."
        )

    def test_has_at_least_one_h2(self, skill_dir: Path) -> None:
        """Skill should have at least one ## section for structure."""
        md = skill_dir / "SKILL.md"
        if not md.exists():
            pytest.skip(f"No SKILL.md in {skill_dir.name}")
        if skill_dir.name in _MINIMAL_BODY_ALLOWLIST:
            pytest.skip(f"{skill_dir.name} is in minimal body allowlist")

        body = _get_body(md)
        h2_count = len(re.findall(r"^##\s+", body, re.MULTILINE))
        assert h2_count >= 1, (
            f"Skill '{skill_dir.name}' has no ## sections. "
            f"Skills need at least one H2 for structure."
        )

    def test_no_untracked_todo_fixme(self, skill_dir: Path) -> None:
        """Flag TODO/FIXME/HACK markers that might be forgotten."""
        md = skill_dir / "SKILL.md"
        if not md.exists():
            pytest.skip(f"No SKILL.md in {skill_dir.name}")

        text = md.read_text(encoding="utf-8")
        # Only flag code-style TODO markers (e.g. "TODO:", "# TODO", "// TODO")
        # Not prose mentions (e.g. "contains a TODO" or "⏳ TODO")
        bare_markers = re.findall(
            r"^[\s#/*]*\b(TODO|FIXME|HACK|XXX)\s*:",
            text,
            re.MULTILINE,
        )
        assert len(bare_markers) == 0, (
            f"Skill '{skill_dir.name}' has {len(bare_markers)} untracked markers: "
            f"{bare_markers}. Add a tracking reference like TODO(BKL-123) or remove."
        )
