#!/usr/bin/env bun
/**
 * cli/commands/portal.ts — atlas portal subcommand (TypeScript)
 *
 * Provides sync/status/diff commands for the DevHub Cockpit portal.
 *
 * Used by: cli/index.ts (TypeScript entrypoint for node/bun)
 * Shell counterpart: scripts/atlas-modules/portal.sh (bash, sourced by atlas())
 *
 * Auth: reads ATLAS_HOOK_TOKEN from env (generated by T8 setup).
 * Endpoint base: DEVHUB_URL (default: http://localhost:8001).
 *
 * SP-DEVHUB-COCKPIT Wave 2 — T10
 * @author AXOIQ
 * @since 2026-04-26
 */

// ─── Types ────────────────────────────────────────────────────

interface SyncPayload {
	session_id: string;
	source: "atlas-cli";
	auto: boolean;
	feature_id?: string;
}

interface SyncResponse {
	status?: string;
	sync_id?: string;
	id?: string;
	triggered_at?: string;
	timestamp?: string;
	files_synced?: string[] | number;
	files?: string[];
}

interface HealthResponse {
	status?: string;
	last_sync_at?: string;
	last_sync?: string;
	sync_count?: number | string;
	pending_changes?: number;
	version?: string;
	drift?: { items?: DriftItem[]; changes?: DriftItem[] } | DriftItem[];
	changes?: DriftItem[];
	drift_count?: number;
}

interface AppEntry {
	name?: string;
	app?: string;
	health?: string;
	status?: string;
	last_sync_at?: string;
	last_sync?: string;
	url?: string;
}

interface EcosystemResponse {
	apps?: AppEntry[];
	services?: AppEntry[];
	data?: AppEntry[];
}

interface DriftItem {
	path?: string;
	file?: string;
	type?: string;
	kind?: string;
	severity?: string;
}

// ─── Helpers ──────────────────────────────────────────────────

function baseUrl(): string {
	return process.env.DEVHUB_URL ?? "http://localhost:8001";
}

/** Resolve auth token: ATLAS_HOOK_TOKEN → ~/.env fallback */
async function resolveToken(): Promise<string | null> {
	if (process.env.ATLAS_HOOK_TOKEN) return process.env.ATLAS_HOOK_TOKEN;

	// Try ~/.env file
	const envPath = `${process.env.HOME ?? "/root"}/.env`;
	try {
		const { readFileSync } = await import("node:fs");
		const content = readFileSync(envPath, "utf-8");
		const match = content.match(/^ATLAS_HOOK_TOKEN=["']?([^"'\n]+)["']?/m);
		if (match?.[1]) return match[1];
	} catch {
		// File not found or unreadable — silent
	}
	return null;
}

/** Pad / truncate string to fixed width */
function col(value: string, width: number): string {
	if (value.length >= width) return value.slice(0, width);
	return value.padEnd(width);
}

/** Pretty-print JSON to stdout */
function pp(data: unknown): void {
	console.log(JSON.stringify(data, null, 2));
}

/** Build auth headers for a request */
async function authHeaders(): Promise<HeadersInit> {
	const token = await resolveToken();
	const base: HeadersInit = { Accept: "application/json" };
	if (token) return { ...base, Authorization: `Bearer ${token}` };
	return base;
}

/** GET <path>, returns parsed JSON or null on error */
async function apiGet<T>(path: string): Promise<T | null> {
	const url = `${baseUrl()}/api/v1${path}`;
	try {
		const res = await fetch(url, { headers: await authHeaders(), signal: AbortSignal.timeout(10_000) });
		if (!res.ok) return null;
		return (await res.json()) as T;
	} catch {
		return null;
	}
}

/** POST <path> with JSON body, returns parsed JSON or null on error */
async function apiPost<T>(path: string, body: unknown): Promise<T | null> {
	const url = `${baseUrl()}/api/v1${path}`;
	try {
		const res = await fetch(url, {
			method: "POST",
			headers: { ...(await authHeaders()), "Content-Type": "application/json" },
			body: JSON.stringify(body),
			signal: AbortSignal.timeout(10_000),
		});
		if (!res.ok) return null;
		return (await res.json()) as T;
	} catch {
		return null;
	}
}

// ─── sync ─────────────────────────────────────────────────────

async function cmdSync(args: string[]): Promise<void> {
	let featureId = "";
	let autoMode = false;
	let jsonMode = false;

	for (let i = 0; i < args.length; i++) {
		const arg = args[i];
		if (arg === "--feature" || arg === "-f") {
			featureId = args[++i] ?? "";
		} else if (arg?.startsWith("--feature=")) {
			featureId = arg.slice("--feature=".length);
		} else if (arg === "--auto") {
			autoMode = true;
		} else if (arg === "--json") {
			jsonMode = true;
		} else if (arg === "--help" || arg === "-h" || arg === "help") {
			printSyncHelp();
			return;
		}
	}

	const payload: SyncPayload = {
		session_id: process.env.CLAUDE_SESSION_ID ?? "cli",
		source: "atlas-cli",
		auto: autoMode,
	};
	if (featureId) payload.feature_id = featureId;

	if (!jsonMode) {
		console.log("\n  \x1b[1mPortal Sync\x1b[0m");
		if (featureId) console.log(`  Feature:   \x1b[36m${featureId}\x1b[0m`);
		if (autoMode) console.log("  Mode:      \x1b[36mauto\x1b[0m");
		console.log(`  Endpoint:  ${baseUrl()}/api/v1/devhub/sync/auto`);
		console.log("  ──────────────────────────────────────────\n");
	}

	const data = await apiPost<SyncResponse>("/devhub/sync/auto", payload);

	if (!data) {
		console.error("  ⚠️  Sync endpoint unreachable — DevHub may not be running");
		console.error("  Hint: Start backend with `docker compose up -d`\n");
		process.exit(1);
	}

	if (jsonMode) {
		pp(data);
		return;
	}

	const ok = ["queued", "ok", "accepted", "synced", "success"].includes(data.status ?? "");
	const icon = ok ? "✅" : "⚠️ ";
	console.log(`  ${icon} ${data.status ?? "?"}`);
	if (data.sync_id ?? data.id) console.log(`  ID:       ${data.sync_id ?? data.id}`);
	if (data.triggered_at ?? data.timestamp) console.log(`  Time:     ${data.triggered_at ?? data.timestamp}`);
	const files = data.files_synced ?? data.files;
	if (Array.isArray(files) && files.length) console.log(`  Files:    ${files.length} synced`);
	else if (files) console.log(`  Files:    ${files}`);
	console.log();
}

function printSyncHelp(): void {
	console.log(`atlas portal sync [flags] — trigger DevHub portal sync

POST /api/v1/devhub/sync/auto

Flags:
  --feature <id>    Sync a specific feature by ID
  --auto            Auto-sync mode (uses last known state)
  --json            Raw JSON output

Auth:
  ATLAS_HOOK_TOKEN  Bearer token (scoped to portal:sync-only)
  DEVHUB_URL        Override base URL (default: http://localhost:8001)

Examples:
  atlas portal sync
  atlas portal sync --feature FE-42
  atlas portal sync --auto
  atlas portal sync --json`);
}

// ─── status ───────────────────────────────────────────────────

async function cmdStatus(args: string[]): Promise<void> {
	const jsonMode = args.includes("--json");

	if (!jsonMode) {
		console.log("\n  \x1b[1mPortal Status\x1b[0m");
		console.log("  ────────────────────────────────────────────────────────────────────\n");
	}

	const health = await apiGet<HealthResponse>("/devhub/health");
	if (!health) {
		console.error(`  ❌ DevHub unreachable at ${baseUrl()}`);
		console.error("  Hint: Set DEVHUB_URL or start backend with `docker compose up -d`\n");
		process.exit(1);
	}

	const eco = await apiGet<EcosystemResponse | AppEntry[]>("/devhub/ecosystem");

	if (jsonMode) {
		console.log("=== /devhub/health ===");
		pp(health);
		if (eco) {
			console.log("\n=== /devhub/ecosystem ===");
			pp(eco);
		}
		return;
	}

	// Health summary
	const status = health.status ?? "?";
	const lastSync = health.last_sync_at ?? health.last_sync ?? "N/A";
	const syncCount = health.sync_count ?? "?";
	const pending = health.pending_changes ?? 0;
	const version = health.version ?? "?";
	const hIcon = ["healthy", "ok"].includes(status) ? "✅" : status === "degraded" ? "⚠️ " : "❌";
	console.log(`  ${hIcon} ${status.toUpperCase().padEnd(12)}  v${version}`);
	console.log(`  Last sync:   ${lastSync}`);
	console.log(`  Total syncs: ${syncCount}`);
	if (pending) console.log(`  Pending:     ${pending} change(s) awaiting sync`);

	// Ecosystem table
	const apps: AppEntry[] = Array.isArray(eco)
		? eco
		: ((eco as EcosystemResponse)?.apps ?? (eco as EcosystemResponse)?.services ?? (eco as EcosystemResponse)?.data ?? []);

	if (apps.length > 0) {
		console.log(`\n  \x1b[1mApplications\x1b[0m`);
		console.log(`  ${col("", 3)}${col("App", 22)} ${col("Health", 12)} ${col("Last Sync", 26)} ${col("URL", 22)}`);
		console.log("  ────────────────────────────────────────────────────────────────────");
		for (const app of apps) {
			const name = col(app.name ?? app.app ?? "", 22);
			const healthVal = col(app.health ?? app.status ?? "?", 12);
			const ls = col(app.last_sync_at ?? app.last_sync ?? "—", 26);
			const url = col(app.url ?? "", 22);
			const aIcon = ["healthy", "ok", "green"].includes(app.health ?? app.status ?? "")
				? "✅"
				: ["degraded", "warn"].includes(app.health ?? app.status ?? "")
					? "⚠️ "
					: "❌";
			console.log(`  ${aIcon}  ${name} ${healthVal} ${ls} ${url}`);
		}
	} else {
		console.log("\n  \x1b[2m(ecosystem endpoint not available)\x1b[0m");
	}

	console.log(`\n  \x1b[2mBase: ${baseUrl()}\x1b[0m\n`);
}

// ─── diff ─────────────────────────────────────────────────────

async function cmdDiff(args: string[]): Promise<void> {
	let since = "";
	let jsonMode = false;

	for (let i = 0; i < args.length; i++) {
		const arg = args[i];
		if (arg === "--since-last-week") {
			const d = new Date(Date.now() - 7 * 24 * 60 * 60 * 1000);
			since = d.toISOString().replace(/\.\d+Z$/, "Z");
		} else if (arg?.startsWith("--since=")) {
			since = arg.slice("--since=".length);
		} else if (arg === "--since") {
			since = args[++i] ?? "";
		} else if (arg === "--json") {
			jsonMode = true;
		} else if (arg === "--help" || arg === "-h" || arg === "help") {
			printDiffHelp();
			return;
		}
	}

	const qs = since ? `?since=${encodeURIComponent(since)}` : "";

	if (!jsonMode) {
		console.log("\n  \x1b[1mPortal Drift Report\x1b[0m");
		if (since) console.log(`  Since:  \x1b[36m${since}\x1b[0m`);
		console.log("  ──────────────────────────────────────────────────────\n");
	}

	const data = await apiGet<HealthResponse>(`/devhub/health${qs}`);
	if (!data) {
		console.error(`  ❌ DevHub unreachable at ${baseUrl()}\n`);
		process.exit(1);
	}

	if (jsonMode) {
		pp(data);
		return;
	}

	const status = data.status ?? "?";
	const lastSync = data.last_sync_at ?? data.last_sync ?? "N/A";

	// Collect drift items
	let driftItems: DriftItem[] = [];
	if (Array.isArray(data.drift)) {
		driftItems = data.drift;
	} else if (data.drift && typeof data.drift === "object") {
		driftItems = data.drift.items ?? data.drift.changes ?? [];
	} else if (Array.isArray(data.changes)) {
		driftItems = data.changes;
	}
	const driftCount = data.drift_count ?? driftItems.length;

	const icon = ["healthy", "ok"].includes(status) ? "✅" : "⚠️ ";
	console.log(`  ${icon} Status:    ${status}`);
	console.log(`  Last sync: ${lastSync}`);
	console.log(`  Drift:     ${driftCount} item(s)`);

	if (driftItems.length > 0) {
		console.log();
		console.log(`  ${col("File", 42)} ${col("Type", 18)} Severity`);
		console.log(`  ${"─".repeat(42)} ${"─".repeat(18)} ${"─".repeat(10)}`);
		const shown = driftItems.slice(0, 20);
		for (const item of shown) {
			const path = col(item.path ?? item.file ?? "", 42);
			const kind = col(item.type ?? item.kind ?? "change", 18);
			const severity = item.severity ?? "medium";
			const sevIcon = ["critical", "high"].includes(severity) ? "🔴" : severity === "medium" ? "🟡" : "🟢";
			console.log(`  ${path} ${kind} ${sevIcon} ${severity}`);
		}
		if (driftItems.length > 20) {
			console.log(`  ... and ${driftItems.length - 20} more item(s)`);
		}
	} else {
		console.log("\n  ✅ No drift detected — portal is in sync");
	}

	console.log();
}

function printDiffHelp(): void {
	console.log(`atlas portal diff [flags] — show DevHub portal drift report

GET /api/v1/devhub/health

Flags:
  --since-last-week     Show drift from the past 7 days
  --since <ISO8601>     Show drift since a specific timestamp
  --json                Raw JSON output

Auth:
  ATLAS_HOOK_TOKEN  Bearer token
  DEVHUB_URL        Override base URL (default: http://localhost:8001)

Examples:
  atlas portal diff
  atlas portal diff --since-last-week
  atlas portal diff --since 2026-04-19T00:00:00Z
  atlas portal diff --json`);
}

// ─── Main export ──────────────────────────────────────────────

/** Main portal command dispatcher — called from cli/index.ts */
export async function portalCmd(args: string[]): Promise<void> {
	const sub = args[0] ?? "help";
	const rest = args.slice(1);

	switch (sub) {
		case "sync":
		case "s":
			await cmdSync(rest);
			break;
		case "status":
		case "st":
			await cmdStatus(rest);
			break;
		case "diff":
		case "d":
			await cmdDiff(rest);
			break;
		case "help":
		case "--help":
		case "-h":
		case "":
			printPortalHelp();
			break;
		default:
			console.error(`Unknown portal subcommand: '${sub}'. Run 'atlas portal help'.`);
			process.exit(1);
	}
}

function printPortalHelp(): void {
	console.log(`atlas portal — DevHub cockpit sync/status/diff commands

Subcommands:
  sync [--feature <id>] [--auto]   Trigger portal sync (POST /devhub/sync/auto)
  status                           App health + last sync table (5+ apps)
  diff [--since-last-week]         Drift report (GET /devhub/health)

Aliases: s=sync, st=status, d=diff

Global flags:
  --json      Raw JSON output (all commands)
  --help, -h  Show command help

Auth (in order of precedence):
  ATLAS_HOOK_TOKEN   Bearer token scoped to portal:sync-only
  DEVHUB_URL         Override base URL (default: http://localhost:8001)

Examples:
  atlas portal sync
  atlas portal sync --feature FE-42 --json
  atlas portal status
  atlas portal diff --since-last-week
  atlas portal diff --json`);
}
